# Generated by Django 5.2.7 on 2025-10-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0002_rename_timestamp_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
