# Generated by Django 5.2.7 on 2025-10-10 05:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0003_alter_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guide_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Step-by-step instructions for using/installing the product', size=None),
        ),
    ]
