# Generated by Django 5.2.7 on 2025-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0004_product_guide_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_product',
            field=models.CharField(blank=True, help_text='Stores the last product referenced in this session', max_length=100, null=True),
        ),
    ]
