# Generated by Django 5.2.7 on 2025-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0006_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_data',
            field=models.JSONField(blank=True, help_text='Stores temporary data for the conversation flow', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_step',
            field=models.CharField(default='greeting', help_text='Current step in the chatbot conversation flow', max_length=50),
        ),
    ]
