# Generated by Django 5.2.7 on 2025-10-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0007_chatsession_conversation_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('selected_panel', models.CharField(blank=True, help_text='Panel selected by user', max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, help_text="User's stated purpose for the panel", max_length=100, null=True)),
                ('user_interests', models.JSONField(blank=True, help_text='Tracked user interests and preferences', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexa.chatsession')),
            ],
        ),
    ]
