# Generated by Django 5.2.7 on 2025-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0008_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='suggested_products',
            field=models.JSONField(blank=True, help_text='Suggested related products (controllers, power supplies, etc.)', null=True),
        ),
    ]
