# Generated by Django 5.2.7 on 2025-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0009_chatlog_suggested_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='configuration_summary',
            field=models.TextField(blank=True, help_text='Final configuration summary when user saves', null=True),
        ),
    ]
