# Generated by Django 5.2.7 on 2025-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alexa', '0010_chatlog_configuration_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, help_text='Detected intent for the message', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, help_text="Bot's response to the message", null=True),
        ),
    ]
